# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_auto_20170320_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Artist')),
            ],
        ),
    ]
