# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_artistsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsummary',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='browse.Artist'),
        ),
    ]
