# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:11
from __future__ import unicode_literals

import arcane.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_auto_20170328_0311'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='USA', max_length=3)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=arcane.users.models.upload_user_avatar)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Artist')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Settings')),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='listener',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
