# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170328_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to=settings.AUTH_USER_MODEL),
        ),
    ]
